package _42.spring.service.services;

import _42.spring.service.config.TestApplicationConfig;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.jdbc.core.JdbcTemplate;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import javax.sql.DataSource;

class UsersServiceImplTest {
    private AnnotationConfigApplicationContext context;
    private UsersService usersService;
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUp() {
        context = new AnnotationConfigApplicationContext(TestApplicationConfig.class);
        usersService = context.getBean(UsersService.class);

        DataSource dataSource = context.getBean(
            "hikariDataSource",
            DataSource.class
        );

        jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("DROP TABLE IF EXISTS users_ex02");
        jdbcTemplate.execute("""
            CREATE TABLE users_ex02 (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email VARCHAR(255) NOT NULL,
                password VARCHAR(255) NOT NULL
            )
        """);
    }

    @Test
    void signUpReturnsTemporaryPassword() {
        String password = usersService.signUp("test@example.com");

        assertNotNull(password);
        assertFalse(password.isBlank());

        String storedPassword = jdbcTemplate.queryForObject(
            "SELECT password FROM users_ex02 WHERE email = ?",
            String.class,
            "test@example.com"
        );

        assertEquals(password, storedPassword);
    }
}